[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin=lib/openzeppelin-contracts/contracts"
]

[lint]
exclude_lints = ["erc20-unchecked-transfer"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
