[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
libs = ["contracts/lib"]
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"
remappings = [
  "@openzeppelin=contracts/lib/openzeppelin-contracts/contracts"
]

[lint]
exclude_lints = ["erc20-unchecked-transfer"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
